/* Every symbol the capture driver interposes with -Wl,--wrap=<sym>. ONE list:
 * build.sh generates its --wrap flags from it, and wrap_fired.c reports a fire
 * count for each entry. A wrapper added without an entry here fails to link
 * (its __real_ symbol is undefined); an entry without a wrapper fails to link
 * (its __wrap_ symbol is undefined). So the two cannot drift. */
ZEN_WRAP(svt_od_ec_encode_cdf_q15)
ZEN_WRAP(svt_od_ec_encode_bool_q15)
ZEN_WRAP(svt_od_ec_encode_bool_eq_q15)
ZEN_WRAP(svt_od_ec_enc_init)
ZEN_WRAP(svt_od_ec_enc_reset)
ZEN_WRAP(svt_od_ec_enc_done)
ZEN_WRAP(svt_av1_loop_filter_init)
ZEN_WRAP(svt_av1_loop_filter_frame)
ZEN_WRAP(svt_aom_txb_estimate_coeff_bits)
ZEN_WRAP(svt_aom_partition_rate_cost)
ZEN_WRAP(svt_aom_pick_partition)
ZEN_WRAP(svt_aom_pick_partition_pd0)
ZEN_WRAP(svt_aom_estimate_syntax_rate)
ZEN_WRAP(svt_aom_intra_fast_cost)
ZEN_WRAP(svt_aom_inter_fast_cost)
ZEN_WRAP(svt_aom_update_mi_map)
ZEN_WRAP(svt_aom_update_stats)
ZEN_WRAP(svt_aom_full_loop_uv)
ZEN_WRAP(svt_av1_intra_prediction)
ZEN_WRAP(svt_aom_get_intra_uv_fast_rate)
ZEN_WRAP(svt_aom_full_cost)
ZEN_WRAP(svt_aom_full_cost_pd0)
ZEN_WRAP(svt_aom_quantize_inv_quantize)
ZEN_WRAP(svt_aom_sig_deriv_enc_dec_pd0)
ZEN_WRAP(svt_av1_reset_cdf_symbol_counters)
ZEN_WRAP(svt_aom_motion_estimation_b64)
ZEN_WRAP(svt_av1_find_best_sub_pixel_tree_pruned)
ZEN_WRAP(svt_av1_compute_qdelta_by_rate)
ZEN_WRAP(svt_aom_inter_pu_prediction_av1)
ZEN_WRAP(svt_aom_global_motion_estimation)
ZEN_WRAP(svt_aom_gm_get_params_cost)
ZEN_WRAP(svt_av1_refine_integerized_param)
ZEN_WRAP(svt_av1_warp_error)
ZEN_WRAP(svt_aom_wm_motion_refinement)
ZEN_WRAP(svt_aom_estimate_transform)
ZEN_WRAP(svt_aom_encode_sb)
ZEN_WRAP(svt_aom_estimate_coefficients_rate)
ZEN_WRAP(svt_aom_write_modes_sb)
ZEN_WRAP(svt_aom_generate_av1_mvp_table)
ZEN_WRAP(svt_aom_update_part_stats)
ZEN_WRAP(svt_aom_quantize_inv_quantize_light)
ZEN_WRAP(svt_aom_inv_transform_recon_wrapper)
ZEN_WRAP(svt_aom_product_full_mode_decision)
ZEN_WRAP(svt_av1_get_q_index_from_qstep_ratio)
ZEN_WRAP(svt_av1_rc_init_sb_qindex)
ZEN_WRAP(svt_av1_rc_calc_qindex_crf_cqp)
ZEN_WRAP(svt_aom_set_tuned_blk_lambda)
