#!/usr/bin/env python3
"""Transcribe C dc/ac_qlookup_10_QTX (inv_transforms.c:3373-3506) into
Rust static tables for crates/svtav1-encoder/src/bd10_qlookup_tables.rs.

Written under the 2026-07-17 bulk-write directive; NOT yet run. Usage:
  python3 xtask/transcribe_bd10_qlookup.py \
      /root/svtav1/Source/Lib/Codec/inv_transforms.c \
      crates/svtav1-encoder/src/bd10_qlookup_tables.rs
Then in bd10.rs replace the unimplemented!() placeholders per its
PORT-NOTE. Follows the same shape as xtask/transcribe_qm.py.
"""
import re
import sys


def extract(src: str, name: str) -> list[int]:
    # Matches: static const int16_t <name>[QINDEX_RANGE] = { ... };
    m = re.search(rf"{name}\s*\[[^\]]*\]\s*=\s*\{{(.*?)\}};", src, re.S)
    if not m:
        raise SystemExit(f"table {name} not found")
    vals = [int(v) for v in re.findall(r"-?\d+", m.group(1))]
    if len(vals) != 256:
        raise SystemExit(f"{name}: expected 256 entries, got {len(vals)}")
    return vals


def emit(name: str, vals: list[int]) -> str:
    rows = []
    for i in range(0, 256, 8):
        rows.append("    " + ", ".join(str(v) for v in vals[i : i + 8]) + ",")
    body = "\n".join(rows)
    return (
        f"/// C {name} (inv_transforms.c:3373-3506), machine-transcribed.\n"
        f"pub static {name.upper().replace('_QTX', '')}: [i16; 256] = [\n{body}\n];\n"
    )


def main() -> None:
    c_path, out_path = sys.argv[1], sys.argv[2]
    src = open(c_path).read()
    out = [
        "// GENERATED by xtask/transcribe_bd10_qlookup.py — do not edit.\n"
        "// Source: Lib/Codec/inv_transforms.c dc/ac_qlookup_10_QTX.\n"
    ]
    for name in ("dc_qlookup_10_QTX", "ac_qlookup_10_QTX"):
        out.append(emit(name, extract(src, name)))
    open(out_path, "w").write("\n".join(out))
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
