#!/usr/bin/env bash
# Per-lint clippy inventory, pinned like the PORT-NOTE and refusal ledgers.
#
#   tools/clippy_inventory.sh --check   # exit 1 if the inventory drifted (CI)
#   tools/clippy_inventory.sh           # rewrite the baseline
#
# WHY A PINNED INVENTORY RATHER THAN `-D warnings`
#
# The workspace carries 39 pre-existing clippy occurrences across 25 lints
# (measured 2026-09-09). A `-D warnings` job cannot land green today, and the
# alternatives usually reached for -- `|| true`, `continue-on-error` -- produce a
# check that CANNOT FAIL, which is worse than no check at all.
#
# So this pins the exact per-lint counts. A NEW lint, or MORE of an existing one,
# is red. FEWER is also red, with a message telling you to re-record in the same
# commit -- that is deliberate: it keeps the baseline honest and makes cleanups
# visible in review instead of silently loosening the gate.
#
# CACHING GOTCHA, the reason this script exists at all rather than a one-line CI
# step: cargo does NOT re-emit warnings for crates it did not recompile. A plain
# `cargo clippy` on a warm target/ prints ZERO warnings and would make this gate
# vacuously green. The crate roots are touched first to force re-emission.
set -euo pipefail

HERE=$(cd "$(dirname "$0")" && pwd)
RS_ROOT=$(cd "$HERE/.." && pwd)
BASELINE="$RS_ROOT/benchmarks/clippy_inventory.txt"
MODE="${1:-}"

cd "$RS_ROOT"
# Force re-emission (see CACHING GOTCHA above).
find crates svtav1 -name lib.rs -o -name main.rs 2>/dev/null | grep -v '/target/' | xargs -r touch

LOG="${TMPDIR:-/tmp}/clippy_inventory.$$.log"
cargo clippy --workspace --locked --all-targets >"$LOG" 2>&1 || {
    echo "clippy_inventory: clippy FAILED to run (this is an error, not a lint count)" >&2
    tail -30 "$LOG" >&2
    exit 1
}

CURRENT="${TMPDIR:-/tmp}/clippy_inventory.$$.txt"
grep -oE 'clippy::[a-z_]+' "$LOG" | sort | uniq -c | awk '{printf "%s %s\n", $2, $1}' | sort >"$CURRENT"

if [ "$MODE" != "--check" ]; then
    {
        echo "# Generated by tools/clippy_inventory.sh — do not edit by hand."
        echo "# Per-lint occurrence counts from: cargo clippy --workspace --locked --all-targets"
        echo "# Total: $(awk '{s+=$2} END {print s+0}' "$CURRENT") occurrences across $(wc -l <"$CURRENT") lints."
        cat "$CURRENT"
    } >"$BASELINE"
    echo "clippy_inventory: wrote $BASELINE ($(awk '{s+=$2} END {print s+0}' "$CURRENT") occurrences)"
    exit 0
fi

[ -f "$BASELINE" ] || { echo "clippy_inventory: no baseline; run $0 with no args" >&2; exit 2; }
grep -v '^#' "$BASELINE" | sort >"${CURRENT}.base"

if diff -u "${CURRENT}.base" "$CURRENT" >"${CURRENT}.diff"; then
    echo "clippy_inventory: current ($(awk '{s+=$2} END {print s+0}' "$CURRENT") occurrences across $(wc -l <"$CURRENT") lints)"
    exit 0
fi

echo "clippy_inventory: DRIFT — the clippy inventory no longer matches the baseline." >&2
echo "  '-' is the baseline, '+' is what clippy reports now:" >&2
sed -n '3,$p' "${CURRENT}.diff" >&2
echo >&2
echo "  A NEW lint or a HIGHER count is a regression: fix it." >&2
echo "  A LOWER count means you cleaned something up: re-record with" >&2
echo "    tools/clippy_inventory.sh    (and say so in the commit message)" >&2
exit 1
