#!/usr/bin/env bash
# Regenerate (or --check) the PORT-NOTE(unverified) index block in CLAUDE.md.
#
# WHY THIS EXISTS. `PORT-NOTE(unverified)` is this port's verification-debt
# ledger: grep it and you have the complete list of places whose bit-exactness
# is asserted but not yet proven against C. CLAUDE.md carried a hand-maintained
# index of that ledger, and a publication audit (issue #8) found it had drifted
# BOTH WAYS — under-counting palette.rs (6 listed vs 10 real) and leaf_funnel.rs
# (2 vs 3), omitting intrabc_pred.rs and a pipeline.rs marker entirely, and
# still listing two markers that had been cleared.
#
# A hand-maintained index of a mechanically-checkable fact will always drift.
# The fix is not to correct it once; it is to generate it and gate it, so the
# next drift is a red build instead of a discovery three months later.
#
#   tools/portnote_index.sh            # rewrite the block in CLAUDE.md
#   tools/portnote_index.sh --check    # exit 1 if the block is stale (CI)
#
# The block is delimited by HTML comments so the prose around it stays
# hand-written; only the counts are generated.
set -uo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
RS_ROOT=$(cd "$HERE/.." && pwd)
cd "$RS_ROOT"

DOC=CLAUDE.md
BEGIN='<!-- PORT-NOTE-INDEX:BEGIN (generated by tools/portnote_index.sh — do not edit by hand) -->'
END='<!-- PORT-NOTE-INDEX:END -->'

generate() {
    local total
    total=$(grep -r "PORT-NOTE(unverified)" --include="*.rs" crates 2>/dev/null | wc -l | tr -d ' ')
    printf '%s\n' "$BEGIN"
    echo
    echo "**${total} unverified markers**, by file. Regenerate with"
    echo '`tools/portnote_index.sh`; `--check` is a CI gate, so this cannot drift.'
    echo 'Each marker names a spot whose bit-exactness vs C is ASSERTED but not'
    echo 'PROVEN. Clearing one means deleting the marker in the same commit as the'
    echo 'evidence (an FFI parity test, an identity cell, or a differential).'
    echo
    echo '| file | markers |'
    echo '|---|---|'
    grep -rc "PORT-NOTE(unverified)" --include="*.rs" crates 2>/dev/null \
        | grep -v ':0$' \
        | sort -t: -k2 -rn \
        | while IFS=: read -r f n; do printf '| `%s` | %s |\n' "$f" "$n"; done
    echo
    printf '%s\n' "$END"
}

if ! grep -qF "$BEGIN" "$DOC"; then
    echo "portnote_index: $DOC has no generated block; add the BEGIN/END markers first" >&2
    exit 2
fi

tmp=$(mktemp)
awk -v b="$BEGIN" -v e="$END" '
    index($0, b) { print; skip = 1; next }
    index($0, e) { skip = 0; print; next }
    !skip { print }
' "$DOC" > "$tmp.stripped"

# Rebuild: everything up to BEGIN, the generated body, everything after END.
{
    awk -v b="$BEGIN" 'index($0,b){exit} {print}' "$DOC"
    generate
    awk -v e="$END" 'found{print} index($0,e){found=1}' "$DOC"
} > "$tmp"

if [[ "${1:-}" == "--check" ]]; then
    if diff -q "$DOC" "$tmp" >/dev/null; then
        echo "portnote_index: index is current ($(grep -r 'PORT-NOTE(unverified)' --include='*.rs' crates | wc -l | tr -d ' ') markers)"
        rm -f "$tmp" "$tmp.stripped"
        exit 0
    fi
    echo "portnote_index: CLAUDE.md's PORT-NOTE index is STALE." >&2
    echo "  The ledger of unverified spots no longer matches the source." >&2
    echo "  Run tools/portnote_index.sh and commit the result." >&2
    diff "$DOC" "$tmp" | head -40 >&2
    rm -f "$tmp" "$tmp.stripped"
    exit 1
fi

mv "$tmp" "$DOC"
rm -f "$tmp.stripped"
echo "portnote_index: regenerated ($(grep -r 'PORT-NOTE(unverified)' --include='*.rs' crates | wc -l | tr -d ' ') markers)"
