#!/usr/bin/env python3
"""Transcribe literal tables and scalar FFT expression trees from pinned SVT C.

No algorithm substitution: each declaration/store has to match the small
accepted grammar, otherwise transcription fails. Generated Rust is checked in.
"""
from pathlib import Path
import re
ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / 'reference/svt-av1/Source/Lib/Codec'
DST = ROOT / 'rust/crates/svtav1-encoder/src'
LICENSE = '// Copyright (c) 2017-2018, Alliance for Open Media. BSD-2-Clause and AOM Patent License.\n'

def expr(s):
    s = re.sub(r'constant\(([\d.]+)f\)', r'\1_f32', s)
    s = re.sub(r'load\(input \+ (\d+) \* stride\)', r'input[\1 * stride]', s)
    return s

def main():
    source = (SRC / 'fft_common.h').read_text().replace('\\\n', '\n')
    output = LICENSE + '// Generated by rust/tools/transcribe_film_grain_tables.py from fft_common.h.\n'
    output += '#![allow(clippy::identity_op, clippy::erasing_op, clippy::approx_constant)]\n'
    output += 'fn add(a:f32,b:f32)->f32 { a+b }\nfn sub(a:f32,b:f32)->f32 { a-b }\nfn mul(a:f32,b:f32)->f32 { a*b }\n'
    for kind in ('fft', 'ifft'):
        for n in (2,4,8,16,32):
            body = re.search(r'ret svt_aom_'+kind+r'1d_'+str(n)+r'_.*?\{(.*?)\n\s*\}', source, re.S).group(1)
            output += f'pub(super) fn {kind}{n}(input:&[f32],output:&mut [f32],stride:usize) {{\n'
            stores = 0
            for statement in body.split(';'):
                s = ' '.join(statement.split())
                if not s: continue
                decl = re.fullmatch(r'const T_VEC (\w+)(\[2\])?\s*=\s*(.*)',s)
                store = re.fullmatch(r'store\(output \+ (\d+) \* stride, (.*)\)',s)
                if decl:
                    name, array, value = decl.groups()
                    if array: value = value.replace('{','[').replace('}',']')
                    output += f'let {name} = {expr(value)};\n'
                elif store:
                    output += f'output[{store[1]} * stride] = {expr(store[2])};\n'
                    stores += 1
                else: raise ValueError(s)
            assert stores == n
            output += '}\n'
    (DST / 'film_grain_fft_1d.rs').write_text(output)
    source = (SRC / 'noise_model.c').read_text()
    output = LICENSE + '// Literal half-cosine windows from noise_model.c; do not recompute with cos().\n'
    for n in (2,4,8,16,32,64):
        values = re.search(r'window_function_half_cos_window_'+str(n)+r'\[\d+\] = \{(.*?)\};', source, re.S).group(1)
        values = re.findall(r'[-\d.]+f', values)
        assert len(values) == n*n
        output += f'pub(super) const WINDOW_{n}: [f32; {n*n}] = [\n'
        for i in range(0,len(values),8): output += ', '.join(v[:-1] for v in values[i:i+8])+',\n'
        output += '];\n'
    output += 'pub(super) fn window(n:usize)-> &\'static [f32] { match n {\n'
    for n in (2,4,8,16,32,64): output += f'{n} => &WINDOW_{n},\n'
    output += '_ => panic!("unsupported noise window size"), }}\n'
    (DST / 'film_grain_windows.rs').write_text(output)

if __name__ == '__main__': main()
