#!/usr/bin/env python3
"""List every archmage `incant!` dispatch site and the SIMD tiers it names.

    tools/review/incant_tiers.py [--root rust/] [--missing]

A site whose tier list lacks both `v3` and `v4` runs its scalar arm on every
x86 machine, however wide its vector unit; one lacking `neon` does the same on
aarch64. `--missing` prints only those sites. Output is TSV
(file, line, kernel, tiers, missing) so it sorts and diffs cleanly.

The parse is textual: it reads the balanced parentheses after `incant!` and
takes the LAST `[...]` group as the tier list, which is how every call in this
tree is written. A site it cannot parse is reported with tiers `?` rather than
skipped, so a change in call shape shows up instead of silently vanishing.
"""
import argparse
import pathlib
import re
import sys


def strip_comments(text):
    # Blank `//` comments (doc comments quote `incant!(...)` in prose) while
    # keeping every newline, so line numbers still match the source.
    return re.sub(r"//[^\n]*", lambda m: " " * len(m.group()), text)


def sites(text):
    text = strip_comments(text)
    for m in re.finditer(r"\bincant!\s*\(", text):
        depth, i = 1, m.end()
        while i < len(text) and depth:
            depth += {"(": 1, ")": -1}.get(text[i], 0)
            i += 1
        body = text[m.end():i - 1]
        line = text.count("\n", 0, m.start()) + 1
        kernel = re.match(r"\s*([A-Za-z_][\w:]*)", body)
        groups = re.findall(r"\[([^\[\]]*)\]\s*,?\s*$", body)
        tiers = [t.strip() for t in groups[-1].split(",") if t.strip()] if groups else None
        yield line, kernel.group(1) if kernel else "?", tiers


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(pathlib.Path(__file__).resolve().parents[2]))
    ap.add_argument("--missing", action="store_true", help="only sites missing an x86 or neon tier")
    ap.add_argument("--check", metavar="LEDGER",
                    help="compare the gaps to LEDGER (kernel<TAB>missing per line); fail on any "
                         "new gap AND on any listed gap that is now closed, so the ledger cannot drift")
    ap.add_argument("--write", metavar="LEDGER", help="rewrite LEDGER from the current tree")
    a = ap.parse_args()
    if a.check or a.write:
        a.missing = True
    root = pathlib.Path(a.root)
    rows = []
    for path in sorted(root.glob("crates/*/src/**/*.rs")):
        text = path.read_text(encoding="utf-8")
        for line, kernel, tiers in sites(text):
            if tiers is None:
                missing = "unparsed"
            else:
                gaps = []
                if not {"v3", "v4"} & set(tiers):
                    gaps.append("x86")
                if not any(t.startswith("neon") for t in tiers):
                    gaps.append("neon")
                missing = ",".join(gaps)
            if a.missing and not missing:
                continue
            rows.append((str(path.relative_to(root)), line, kernel,
                         ",".join(tiers) if tiers else "?", missing))
    if a.check or a.write:
        now = sorted({(r[2], r[4]) for r in rows})
        body = "".join(f"{k}\t{m}\n" for k, m in now)
        header = ("# incant! sites that run their scalar arm on one architecture (kernel, missing\n"
                  "# tier family). Generated by tools/review/incant_tiers.py --write; checked in CI\n"
                  "# by --check. Closing a gap = add the tier, then --write. Plan: Phase 5 item 1.\n")
        if a.write:
            pathlib.Path(a.write).write_text(header + body)
            sys.stderr.write(f"incant_tiers: wrote {len(now)} gaps to {a.write}\n")
            return
        want = {tuple(l.split("\t")) for l in pathlib.Path(a.check).read_text().splitlines()
                if l and not l.startswith("#")}
        new, closed = set(now) - want, want - set(now)
        if new or closed:
            for k, m in sorted(new):
                sys.stderr.write(f"  NEW gap     {k}: missing {m}\n")
            for k, m in sorted(closed):
                sys.stderr.write(f"  now CLOSED  {k}: missing {m} (rerun with --write)\n")
            sys.stderr.write("incant_tiers: tier ledger is out of date\n")
            sys.exit(1)
        sys.stderr.write(f"incant_tiers: ledger current ({len(now)} gaps)\n")
        return
    w = sys.stdout.write
    w("file\tline\tkernel\ttiers\tmissing\n")
    for r in rows:
        w("\t".join(map(str, r)) + "\n")
    total = sum(1 for p in root.glob("crates/*/src/**/*.rs")
                for _ in sites(p.read_text(encoding="utf-8")))
    sys.stderr.write(f"{len(rows)} of {total} incant! sites listed\n")


if __name__ == "__main__":
    main()
