//! Differential parity: the machine-transcribed 10-bit quantizer step tables
//! vs the REAL C `svt_aom_dc_quant_qtx` / `svt_aom_ac_quant_qtx` at
//! `EB_TEN_BIT`.
//!
//! `DC_QLOOKUP_10` / `AC_QLOOKUP_10` (`bd10_qlookup_tables.rs`, generated by
//! `xtask/transcribe_bd10_qlookup.py`) are the 256-entry step tables the bd10
//! quant path indexes. They were machine-transcribed from
//! `inv_transforms.c dc/ac_qlookup_10_QTX` and had NO differential coverage —
//! verbatim transcription is this project's WEAKEST evidence tier, and a
//! single wrong step scales every 10-bit coefficient. This pins them against
//! the real exported C symbol for every qindex 0..=255.
//!
//! The C `svt_aom_dc_quant_qtx(qindex, delta, bd)` clamps `qindex + delta` to
//! `[0, MAXQ=255]` then indexes the per-bd table; passing `delta = 0` over the
//! full 0..=255 range exercises every table entry exactly once, so table
//! identity here IS full-range quantizer identity for the bd10 path.

use svtav1_cref as cref;
use svtav1_encoder::bd10::{ac_qlookup_10, dc_qlookup_10, AC_QLOOKUP_10, DC_QLOOKUP_10};

/// Every bd10 DC/AC step-table entry matches the real C quantizer at
/// `EB_TEN_BIT` across the whole qindex range.
#[test]
fn bd10_qlookup_tables_match_c() {
    for q in 0..=255i32 {
        let c_dc = cref::dc_quant_qtx_bd(q, 10);
        let c_ac = cref::ac_quant_qtx_bd(q, 10);
        assert_eq!(
            DC_QLOOKUP_10[q as usize], c_dc,
            "DC_QLOOKUP_10[{q}]: port {} vs C {c_dc}",
            DC_QLOOKUP_10[q as usize]
        );
        assert_eq!(
            AC_QLOOKUP_10[q as usize], c_ac,
            "AC_QLOOKUP_10[{q}]: port {} vs C {c_ac}",
            AC_QLOOKUP_10[q as usize]
        );
        // The public accessors index the same tables — exercise the API too.
        assert_eq!(dc_qlookup_10(q as u8), c_dc, "dc_qlookup_10({q}) accessor");
        assert_eq!(ac_qlookup_10(q as u8), c_ac, "ac_qlookup_10({q}) accessor");
    }
}

/// Harness-soundness cross-check: the new bit-depth-parameterized shim must
/// agree with the pre-existing 8-bit-only shim at `bd = 8`. If this ever
/// diverged, the bd10 assertions above could be comparing against a
/// mis-wired C call rather than the real quantizer — this rules that out
/// without needing the port's own 8-bit table visible here.
#[test]
fn bd_parameterized_shim_agrees_with_8bit_shim_at_bd8() {
    for q in 0..=255i32 {
        assert_eq!(
            cref::dc_quant_qtx_bd(q, 8),
            cref::dc_quant_qtx(q),
            "dc bd-shim vs 8-bit shim at q={q}"
        );
        assert_eq!(
            cref::ac_quant_qtx_bd(q, 8),
            cref::ac_quant_qtx(q),
            "ac bd-shim vs 8-bit shim at q={q}"
        );
    }
}
